FROM postgres
# RUN apt-get update
# RUN apt-get install wget -y
# RUN wget -O pgfutter https://github.com/lukasmartinelli/pgfutter/releases/download/v1.0/pgfutter_linux_amd64
# RUN chmod +x pgfutter
# RUN psql -U postgres -f /var/lib/postgresql/seed.sql