// Generated by CoffeeScript 1.10.0
(function() {
  var path;
  'use strict';
  var app, async, express, http, path, redis, request, serveStatic, server;

  express = require('express');

  request = require('request');

  redis = require('redis');

  path = require('path');

  http = require('http');

  path = require('path');

  async = require('async');

  serveStatic = require('serve-static');

  app = express();

  app.disable('etag');

  app.set('trust proxy', true);

  app.use(serveStatic('./', {
    'index': ['grid.html', 'grid.htm']
  }));

  app.use(serveStatic('./node_modules/bootstrap/dist/js'));

  app.use(serveStatic('./node_modules/bootstrap/dist/css'));

  app.use(serveStatic('./node_modules/jquery/dist'));

  app.use(serveStatic('./bower_components/jquery/dist'));

  app.use(serveStatic('./bower_components/d3'));

  app.use(serveStatic('./bower_components/d3-queue/'));

  app.use(serveStatic('./node_modules/topojson/build'));

  app.use(serveStatic('./bower_components/mapbox.js/'));

  app.use(serveStatic('./bower_components/d3-tip'));

  app.use(serveStatic('./node_modules/mapbox-gl/dist'));

  app.use(serveStatic('./bower_components/leaflet/dist'));

  app.use(serveStatic('./bower_components/crossfilter'));

  app.use(serveStatic('./stylesheets'));

  app.use(serveStatic('./data'));

  app.use(serveStatic('./node_modules/dc'));

  app.use(serveStatic('./scripts'));

  app.get('/', function(req, res) {
    res.render('index', function(err, html) {
      res.send(html);
    });
  });


  /* Start the server */

  server = app.listen(process.env.PORT || '8080', '0.0.0.0', function() {
    console.log('App listening at http://%s:%s', server.address().address, server.address().port);
    console.log('Press Ctrl+C to quit.');
    console.log('checking if adjustments work');
  });

}).call(this);
