`var path`
'use strict'

express = require 'express'
request = require 'request'
# redis = require 'redis'
path = require 'path' 
http = require 'http'
path = require 'path'
async = require 'async'
# redis = require 'redis'
# MongoClient = require('mongodb').MongoClient
serveStatic = require 'serve-static'

# redisHOST = 'redis'

# client = redis.createClient('6379', redisHOST)
# client.on 'error', (err) ->
#   console.log 'Error ' + err
#   return

# client.hgetall 'cityCentroids', (err, object) ->
#   console.log object
#   return



# MongoClient.connect 'mongodb://mongo:27017/atlasdb', (err, db) ->
#   console.log "trying to conncet to mongo`"
#   if err
#     throw err
#   db.collection('cities').find().toArray (err, result) ->
#     if err
#       throw err
#     console.log "results",result
#     return
#   return



Sequelize = require('sequelize')
sequelize = new Sequelize('atlasdb', 'postgres', ''
  host: 'postgresql'
  dialect: 'postgres')


# Model = sequelize.define('model',
#   type: Sequelize.STRING
#   name: Sequelize.STRING)

# sequelize.sync().then(->
#   Model.create
#     type: 'sometype'
#     name: 'somename'
# ).then (type) ->
#   console.log type.get(plain: true)
#   return

app = express()


app.disable 'etag'
app.set 'trust proxy', true
app.use serveStatic('./bower_components/jquery/dist')
app.use serveStatic('./node_modules/bootstrap/dist/js')
app.use serveStatic('./node_modules/bootstrap/dist/css')
app.use serveStatic('./bower_components/d3')
app.use serveStatic('./bower_components/leaflet/dist')
app.use serveStatic('./bower_components/d3-queue/')
app.use serveStatic('./node_modules/topojson/build')
app.use serveStatic('./bower_components/mapbox.js/')
app.use serveStatic('./node_modules/d3-tip')
app.use serveStatic('./node_modules/mapbox-gl/dist')
app.use serveStatic('./node_modules/crossfilter')
app.use serveStatic('./font-awesome')
app.use serveStatic('./stylesheets')

app.use serveStatic('./data')
app.use serveStatic('./node_modules/dc')
app.use serveStatic('./scripts')


app.use (req, res, next) ->
  auth = undefined
  # check whether an autorization header was send    
  if req.headers.authorization
    # only accepting basic auth, so:
    # * cut the starting "Basic " from the header
    # * decode the base64 encoded username:password
    # * split the string at the colon
    # -> should result in an array
    auth = new Buffer(req.headers.authorization.substring(6), 'base64').toString().split(':')
  # checks if:
  # * auth array exists 
  # * first value matches the expected user 
  # * second value the expected password
  if !auth or auth[0] != 'atlas' or auth[1] != 'Atlas0fL1ght1ng'
    # any of the tests failed
    # send an Basic Auth request (HTTP Code: 401 Unauthorized)
    res.statusCode = 401
    # MyRealmName can be changed to anything, will be prompted to the user
    res.setHeader 'WWW-Authenticate', 'Basic realm="Access to atlas is restricted in beta version"'
    # this will displayed in the browser when authorization is cancelled
    res.end 'Unauthorized'
  else
    # continue with processing, user was authenticated
    next()
  return

# ---
# generated by js2coffee 2.2.0


app.use serveStatic('./', 'index': [
  'landing.html'
  'landing.htm'
])

app.get '/', (req, res) ->
  res.render 'index', (err, html) ->
    res.send html
    return
  return


app.get '/grids/:msa', (req, res) ->
  sequelize.query('SELECT * FROM grid WHERE msa = :msa ',
    replacements: msa: "#{req.params.msa}"
    type: sequelize.QueryTypes.SELECT).then (object) ->
      res.json object
      return
    return
  return

app.get '/cities', (req, res) ->
  sequelize.query('SELECT * FROM city', type: sequelize.QueryTypes.SELECT).then (object) ->
    res.json object
    return
  return

app.get '/groups_data', (req, res) ->
  sequelize.query('SELECT * FROM group_data', type: sequelize.QueryTypes.SELECT).then (object) ->
    res.json object
    return
  return

app.get '/city_comparisons_all', (req, res) ->
  sequelize.query('SELECT * FROM city_comparison', type: sequelize.QueryTypes.SELECT).then (object) ->
    res.json object
    return
  return

app.get '/cityComparisonsData', (req, res) ->
  client.hgetall "city_comparison_data", (err, object) ->
    res.json object 
    return
  return



# app.get '/comparisonsData/:datacomponent', (req, res) ->
#   client.hgetall "#{req.params.datacomponent}", (err, object) ->
#     res.json object 
#     return
#   return

app.get '/us_json', (req, res) ->
  sequelize.query('SELECT * FROM us_json', type: sequelize.QueryTypes.SELECT).then (object) ->
    res.json object
    return
  # client.hgetall "us_json", (err, object) ->
  #   res.json object
  #   return 
  return 
 
  # client.get "us_json", (err, object) ->
  #   stringifiedObject = JSON.stringify(object.replace('"',''))
  #   jsonObject = JSON.parse(stringifiedObject)
  #   res.json jsonObject
  #   return
  # return 

app.get '/zipcode_business_geojson/:msa', (req, res) ->
  # sequelize.query("zipcode_business_geojson_#{req.params.msa}", type: sequelize.QueryTypes.SELECT).then (object) ->
  sequelize.query('SELECT * FROM zipcode_business', type: sequelize.QueryTypes.SELECT).then (object) ->
    res.json object
    return
  # client.hgetall "zipcode_business_geojson_#{req.params.msa}", (err, object) ->
  #   res.json object
  #   return
  return 




### Start the server ###

# server = app.listen(process.env.PORT or '8080', '0.0.0.0', ->
#   console.log 'App listening at http://%s:%s', server.address().address, server.address().port
#   console.log 'Press Ctrl+C to quit.'
#   console.log 'checking if adjustments work'
#   return
# )
# export the app object for test
module.exports =
  app: app
  port: 8080