// Generated by CoffeeScript 1.10.0
(function() {
  var path;
  'use strict';
  var Sequelize, app, async, client, express, http, path, redis, redisHOST, request, sequelize, serveStatic, server;

  express = require('express');

  request = require('request');

  redis = require('redis');

  path = require('path');

  http = require('http');

  path = require('path');

  async = require('async');

  redis = require('redis');

  serveStatic = require('serve-static');

  redisHOST = 'redis';

  client = redis.createClient('6379', redisHOST);

  client.on('error', function(err) {
    console.log('Error ' + err);
  });

  Sequelize = require('sequelize');

  sequelize = new Sequelize('atlasdb', 'postgres', '', {
    host: 'postgresql',
    dialect: 'postgres'
  });

  app = express();

  app.disable('etag');

  app.set('trust proxy', true);

  app.use(serveStatic('./bower_components/jquery/dist'));

  app.use(serveStatic('./node_modules/bootstrap/dist/js'));

  app.use(serveStatic('./node_modules/bootstrap/dist/css'));

  app.use(serveStatic('./bower_components/d3'));

  app.use(serveStatic('./bower_components/leaflet/dist'));

  app.use(serveStatic('./bower_components/d3-queue/'));

  app.use(serveStatic('./node_modules/topojson/build'));

  app.use(serveStatic('./bower_components/mapbox.js/'));

  app.use(serveStatic('./node_modules/d3-tip'));

  app.use(serveStatic('./node_modules/mapbox-gl/dist'));

  app.use(serveStatic('./node_modules/crossfilter'));

  app.use(serveStatic('./stylesheets'));

  app.use(serveStatic('./data'));

  app.use(serveStatic('./node_modules/dc'));

  app.use(serveStatic('./scripts'));

  app.use(serveStatic('./', {
    'index': ['grid.html', 'grid.htm']
  }));

  app.get('/', function(req, res) {
    res.render('index', function(err, html) {
      res.send(html);
    });
  });

  app.get('/grids/:msa', function(req, res) {
    sequelize.query('SELECT * FROM grid WHERE msa = :msa ', {
      replacements: {
        msa: "" + req.params.msa
      },
      type: sequelize.QueryTypes.SELECT
    }).then(function(object) {
      res.json(object);
    });
    return;
  });

  app.get('/cities', function(req, res) {
    sequelize.query('SELECT * FROM city', {
      type: sequelize.QueryTypes.SELECT
    }).then(function(object) {
      res.json(object);
    });
  });

  app.get('/city_comparisons_all', function(req, res) {
    sequelize.query('SELECT * FROM city_comparison', {
      type: sequelize.QueryTypes.SELECT
    }).then(function(object) {
      res.json(object);
    });
  });

  app.get('/cityComparisonsData', function(req, res) {
    client.hgetall("city_comparison_data", function(err, object) {
      res.json(object);
    });
  });

  app.get('/comparisonsData/:datacomponent', function(req, res) {
    client.hgetall("" + req.params.datacomponent, function(err, object) {
      res.json(object);
    });
  });

  app.get('/us_json', function(req, res) {
    client.hgetall("us_json", function(err, object) {
      res.json(object);
    });
  });

  app.get('/zipcode_business_geojson/:msa', function(req, res) {
    client.hgetall("zipcode_business_geojson_" + req.params.msa, function(err, object) {
      res.json(object);
    });
  });

  module.exports = app;


  /* Start the server */

  server = app.listen(process.env.PORT || '8080', '0.0.0.0', function() {
    console.log('App listening at http://%s:%s', server.address().address, server.address().port);
    console.log('Press Ctrl+C to quit.');
    console.log('checking if adjustments work');
  });

}).call(this);
