// Generated by CoffeeScript 1.10.0
(function() {
  var cityCentroids, cityColors, data_items, fullName, groupToWords, nightlightColors, typeColors, typeNumberToText;

  cityCentroids = {
    'San Jose': {
      lat: 37.338208,
      lng: -121.886329
    },
    'Orlando': {
      lat: 28,
      lng: -81
    },
    'Milwaukee': {
      lat: 43.038903,
      lng: -87.906474
    },
    'Washington': {
      lat: 39,
      lng: -77
    },
    'Denver': {
      lat: 39,
      lng: -104
    },
    'Chicago': {
      lat: 41.878114,
      lng: -87.629798
    },
    'Pittsburg': {
      lat: 40,
      lng: -79
    },
    'Portland': {
      lat: 45.523062,
      lng: -122.676482
    },
    'Las Vegas': {
      lat: 36.084,
      lng: -115.153739
    },
    'Los Angeles': {
      lat: 34,
      lng: -118
    }
  };

  nightlightColors = {
    '1': '#fff7bc',
    '2': '#fee391',
    '3': '#fec44f',
    '4': '#fee0d2',
    '5': '#fc9272',
    '6': '#de2d26',
    '7': '#deebf7',
    '8': '#9ecae1',
    '9': '#3182bd'
  };

  fullName = {
    'San Jose': 'San Jose-Sunnyvale-Santa Clara, CA',
    'Orlando': 'Orlando-Kissimmee-Sanford, FL',
    'Milwaukee': 'Milwaukee-Waukesha-West Allis, WI',
    'Washington': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
    'Denver': 'Denver-Aurora-Broomfield, CO',
    'Chicago': 'Chicago-Joliet-Naperville, IL-IN-WI',
    'Pittsburg': 'Pittsburgh, PA',
    'Portland': 'Portland-Vancouver-Hillsboro, OR-WA',
    'Las Vegas': 'Las Vegas-Paradise, NV',
    'Los Angeles': 'Los Angeles-Long Beach-Santa Ana, CA'
  };

  cityColors = {
    'San Jose': '#B6DCAE',
    'Orlando': '#F69274',
    'Milwaukee': '#816CB1',
    'Washington': '#FEC652',
    'Denver': '#FCE391',
    'Chicago': '#2982BE',
    'Pittsburg': '#B6AAD3',
    'Portland': '#88C540',
    'Las Vegas': '#E02D27',
    'Los Angeles': '#9CCBE3'
  };

  typeColors = {
    'Large-Slow Growth': '#20c0e2',
    'Rust Belt-Declining': '#62d999',
    'Growth Magnets': '#e9c057',
    'Large-Faster Growth': '#e4587b',
    'New Economy-Quality of Life Hubs': '#f28954',
    'Uncatagorized': '#aaa'
  };

  typeNumberToText = {
    '1': 'Large-Slow Growth',
    '3': 'Rust Belt-Declining',
    '5': 'Growth Magnets',
    '2': 'Large-Faster Growth',
    '4': 'New Economy-Quality of Life Hubs',
    '0': 'Uncatagorized'
  };

  groupToWords = {
    '1': 'Low Income, Low Intensity',
    '2': 'Low Income, Medium Intensity',
    '3': 'Low Income, High Intensity',
    '4': 'Medium Income, Low Intensity',
    '5': 'Medium Income, Medium Intensity',
    '6': 'Medium Income, High Intensity',
    '7': 'High Income, Low Intensity',
    '8': 'High Income, Medium Intensity',
    '9': 'High Income, High Intensity'
  };

  data_items = ["cityCentroids", "nightlightColors", "fullName", "cityColors", "typeColors", "typeNumberToText", "groupToWor"];

  module.exports.cityCentroids = cityCentroids;

  module.exports.nightlightColors = nightlightColors;

  module.exports.fullName = fullName;

  module.exports.cityColors = cityColors;

}).call(this);
