"""empty message

Revision ID: ec949a0dab2d
Revises: None
Create Date: 2016-09-28 23:43:56.798325

"""

# revision identifiers, used by Alembic.
revision = 'ec949a0dab2d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('gmp', sa.Float(), nullable=True),
    sa.Column('popChange', sa.Integer(), nullable=True),
    sa.Column('gridorder', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.Integer(), nullable=True),
    sa.Column('GeoName', sa.String(), nullable=True),
    sa.Column('Pop1', sa.Integer(), nullable=True),
    sa.Column('Pop2', sa.Integer(), nullable=True),
    sa.Column('Density1', sa.Float(), nullable=True),
    sa.Column('Density2', sa.Float(), nullable=True),
    sa.Column('LandArea', sa.Float(), nullable=True),
    sa.Column('GMP2013', sa.Integer(), nullable=True),
    sa.Column('Class', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('averlight', sa.Float(), nullable=True),
    sa.Column('places', sa.Integer(), nullable=True),
    sa.Column('b_diversity', sa.Float(), nullable=True),
    sa.Column('dev_intensity', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('inc_cat', sa.Integer(), nullable=True),
    sa.Column('msa', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('gmp', sa.Integer(), nullable=True),
    sa.Column('popChange', sa.Integer(), nullable=True),
    sa.Column('gridorder', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('us_json',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usjson', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zipcode_business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msa', sa.String(), nullable=True),
    sa.Column('geojson', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode_business')
    op.drop_table('us_json')
    op.drop_table('group_data')
    op.drop_table('grid')
    op.drop_table('city_comparison')
    op.drop_table('city')
    ### end Alembic commands ###
